version: '3'

services:
  website:
    container_name: website
    restart: always
    image: php:apache
    ports:
      - "8080:80"
    depends_on:
      - "api"
    environment:
      - USERNAME=toto
      - PASSWORD=python
    volumes:
      - ./website:/var/www/html/

  api:
    container_name: flask
    restart: always
    build: ./simple_api
    image: simple-api
    ports:
      - 5000:5000